# Generated by Django 4.0 on 2021-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='category_name', max_length=100, verbose_name='category_name')),
                ('descriotion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='high', max_length=6)),
                ('date_added', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='category_tasks', related_query_name='cat_tasks', to='makingform.Category')),
            ],
        ),
    ]
