# Generated by Django 3.2.9 on 2021-11-21 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
