# Generated by Django 4.0 on 2021-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=6)),
                ('date_added', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='category_tasks', related_query_name='cat_tasks', to='TODO.Category')),
            ],
        ),
    ]
