# Generated by Django 3.2.9 on 2021-11-22 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 22, 15, 15, 41, 788280)),
        ),
    ]
