# Generated by Django 3.2.9 on 2021-12-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20211205_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriotion',
            field=models.TextField(default='category'),
            preserve_default=False,
        ),
    ]
