# Generated by Django 3.2.9 on 2021-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_task_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Category',
            field=models.ManyToManyField(related_name='category_tasks', related_query_name='cat_tasks', to='todo.Category'),
        ),
    ]
