# Generated by Django 3.2.9 on 2021-12-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Category',
            new_name='members',
        ),
    ]
