# Generated by Django 3.2.9 on 2021-12-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='members',
            new_name='category',
        ),
    ]
