# Generated by Django 4.0 on 2021-12-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inheritaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('open_year', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['age']},
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritaces.place')),
                ('active', models.BooleanField(default=False)),
                ('food', models.CharField(max_length=100)),
            ],
            bases=('inheritaces.place',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritaces.place')),
                ('customers', models.ManyToManyField(related_name='provider', to='inheritaces.Place')),
            ],
            bases=('inheritaces.place',),
        ),
    ]
