# Generated by Django 4.0 on 2021-12-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritaces', '0002_place_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='open_year',
        ),
    ]
