# Generated by Django 4.0 on 2021-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritaces', '0003_remove_place_open_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'Fiction'), ('n', 'Non_fiction'), ('b', 'Bigraphy')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FictionStory',
            fields=[
            ],
            options={
                'ordering': ['title'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inheritaces.story',),
        ),
    ]
